// Package models provides data structures for the RMS API client.
package models

// TagAction represents an action associated with a tag.
type TagAction struct {
	TagID      int    `json:"tag_id"`
	Action     string `json:"action"`
	CreatedAt  string `json:"created_at"`
	SourceID   int    `json:"source_id"`
	SourceName string `json:"source_name"`
}

// Tag represents a device tag.
type Tag struct {
	CompanyID   int         `json:"company_id"`
	Color       string      `json:"color"`
	UpdatedAt   string      `json:"updated_at"`
	UserID      int         `json:"user_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	CreatedAt   string      `json:"created_at"`
	ID          int         `json:"id"`
	Actions     []TagAction `json:"actions"`
}

// Device represents a Teltonika RMS device (full schema).
type Device struct {
	ID                             int           `json:"id"`
	Name                           string        `json:"name"`
	IMEI                           string        `json:"imei"`
	IMEI2                          string        `json:"imei_2"`
	Serial                         string        `json:"serial"`
	Model                          string        `json:"model"`
	OriginalModel                  string        `json:"original_model"`
	ProductCode                    string        `json:"product_code"`
	CompanyID                      int           `json:"company_id"`
	CompanyName                    string        `json:"company_name"`
	Status                         int           `json:"status"`
	ConnectionState                string        `json:"connection_state"`
	ConnectionType                 string        `json:"connection_type"`
	ConnectionState2               string        `json:"connection_state_2"`
	ConnectionType2                string        `json:"connection_type_2"`
	CreatedAt                      string        `json:"created_at"`
	UpdatedAt                      string        `json:"updated_at"`
	LastConnectionAt               string        `json:"last_connection_at"`
	LastUpdateAt                   string        `json:"last_update_at"`
	Tags                           []Tag         `json:"tags"`
	Mac                            string        `json:"mac"`
	WlanMac                        string        `json:"wlan_mac"`
	Latitude                       float64       `json:"latitude"`
	Longitude                      float64       `json:"longitude"`
	Altitude                       float64       `json:"altitude"`
	UserSetLatitude                float64       `json:"user_set_latitude"`
	UserSetLongitude               float64       `json:"user_set_longitude"`
	Description                    string        `json:"description"`
	BatchNumber                    string        `json:"batch_number"`
	Firmware                       string        `json:"firmware"`
	ModemFirmware                  string        `json:"modem_firmware"`
	ModemFirmware2                 string        `json:"modem_firmware_2"`
	ModemModel                     string        `json:"modem_model"`
	ModemModel2                    string        `json:"modem_model_2"`
	ModemManufacturer              string        `json:"modem_manufacturer"`
	ModemManufacturer2             string        `json:"modem_manufacturer_2"`
	BootloaderVersion              string        `json:"bootloader_version"`
	HardwareRevision               string        `json:"hardware_revision"`
	FWVersion                      string        `json:"fw_version"`
	HWVersion                      string        `json:"hw_version"`
	RouterUptime                   int           `json:"router_uptime"`
	Satellites                     int           `json:"satellites"`
	Signal                         int           `json:"signal"`
	Signal2                        int           `json:"signal_2"`
	RSRP                           float64       `json:"rsrp"`
	RSRP2                          float64       `json:"rsrp_2"`
	RSRQ                           float64       `json:"rsrq"`
	RSRQ2                          float64       `json:"rsrq_2"`
	SINR                           float64       `json:"sinr"`
	SINR2                          float64       `json:"sinr_2"`
	ECIO                           string        `json:"ecio"`
	ECIO2                          string        `json:"ecio_2"`
	RSCP                           string        `json:"rscp"`
	RSCP2                          string        `json:"rscp_2"`
	Operator                       string        `json:"operator"`
	Operator2                      string        `json:"operator_2"`
	OperatorNumber                 string        `json:"operator_number"`
	OperatorNumber2                string        `json:"operator_number_2"`
	MCC                            string        `json:"mcc"`
	MCC2                           string        `json:"mcc_2"`
	MNC                            string        `json:"mnc"`
	MNC2                           string        `json:"mnc_2"`
	LAC                            string        `json:"lac"`
	LAC2                           string        `json:"lac_2"`
	IMSI                           string        `json:"imsi"`
	IMSI2                          string        `json:"imsi_2"`
	ICCID                          string        `json:"iccid"`
	ICCID2                         string        `json:"iccid_2"`
	MobileIP                       string        `json:"mobile_ip"`
	MobileIP2                      string        `json:"mobile_ip_2"`
	WANIP                          string        `json:"wan_ip"`
	CellID                         string        `json:"cell_id"`
	CellID2                        string        `json:"cell_id_2"`
	CellTowerLatitude              Float64String `json:"cell_tower_latitude"`
	CellTowerLongitude             Float64String `json:"cell_tower_longitude"`
	CellTowerLatitude2             Float64String `json:"cell_tower_latitude_2"`
	CellTowerLongitude2            Float64String `json:"cell_tower_longitude_2"`
	CellTowerAccuracy              Float64String `json:"cell_tower_accuracy"`
	CellTowerAccuracy2             Float64String `json:"cell_tower_accuracy_2"`
	GPSMonitoring                  int           `json:"gps_monitoring"`
	HotspotMonitoring              int           `json:"hotspot_monitoring"`
	WirelessMonitoring             int           `json:"wireless_monitoring"`
	StaticMonitoring               int           `json:"static_monitoring"`
	DynamicMonitoring              int           `json:"dynamic_monitoring"`
	VPNMonitoring                  int           `json:"vpn_monitoring"`
	VPNMonitoringInstancesState    int           `json:"vpn_monitoring_instances_state"`
	DDNSMonitoring                 int           `json:"ddns_monitoring"`
	DDNSRulesCount                 int           `json:"ddns_rules_count"`
	MonitoringEnabled              int           `json:"monitoring_enabled"`
	AutoExtendCredit               int           `json:"auto_extend_credit"`
	CreditEnabled                  int           `json:"credit_enabled"`
	CreditActivated                int           `json:"credit_activated"`
	CreditExpireDate               string        `json:"credit_expire_date"`
	DataCreditType                 string        `json:"data_credit_type"`
	DataCreditTypeID               int           `json:"data_credit_type_id"`
	DataCreditTypeName             string        `json:"data_credit_type_name"`
	ManagementCreditType           string        `json:"management_credit_type"`
	ManagementCreditTypeID         int           `json:"management_credit_type_id"`
	ManagementCreditTypeName       string        `json:"management_credit_type_name"`
	ActivationStatus               string        `json:"activation_status"`
	IsAuthenticated                int           `json:"is_authenticated"`
	IsFacelift                     int           `json:"is_facelift"`
	RemainingData                  int           `json:"remaining_data"`
	ConnectionUptime               int           `json:"connection_uptime"`
	ConnectionUptime2              int           `json:"connection_uptime_2"`
	FixStatus                      int           `json:"fix_status"`
	GPSTime                        int           `json:"gps_time"`
	Speed                          float64       `json:"speed"`
	Course                         float64       `json:"course"`
	Temperature                    int           `json:"temperature"`
	Temperature2                   int           `json:"temperature_2"`
	AnalogInput                    string        `json:"analog_input"`
	AnalogCurrentLoop              string        `json:"analog_current_loop"`
	DigitalInput                   int           `json:"digital_input"`
	DigitalInOut0                  int           `json:"digital_inout0"`
	DigitalInOut1                  int           `json:"digital_inout1"`
	DigitalInOut2                  int           `json:"digital_inout2"`
	DigitalIsolatedInput           int           `json:"digital_isolated_input"`
	DigitalNonIsolatedInput4Pin    int           `json:"digital_non_isolated_input_4pin"`
	DigitalOpenCollectorOutput4Pin int           `json:"digital_open_collector_output_4pin"`
	OpenCollectorOutput            int           `json:"open_collector_output"`
	RelayOutput                    string        `json:"relay_output"`
	RelayOutput2                   int           `json:"relay_output_2"`
	RelayOutputCfg                 string        `json:"relay_output_cfg"`
	OCOutputCfg                    string        `json:"oc_output_cfg"`
	DryWetInput0                   int           `json:"dry_wet_input0"`
	DryWetInput1                   int           `json:"dry_wet_input1"`
	SimSlot                        int           `json:"sim_slot"`
	SimSlot2                       int           `json:"sim_slot_2"`
	SimState                       string        `json:"sim_state"`
	SimState2                      string        `json:"sim_state_2"`
	PinState                       string        `json:"pin_state"`
	PinState2                      string        `json:"pin_state_2"`
	Mqtt                           int           `json:"mqtt"`
	Received                       int           `json:"received"`
	Received2                      int           `json:"received_2"`
	Sent                           int           `json:"sent"`
	Sent2                          int           `json:"sent_2"`
	IoMonitoring                   int           `json:"io_monitoring"`
	Accuracy                       int           `json:"accuracy"`
	FailedAuthReason               int           `json:"failed_auth_reason"`
	NetworkState                   string        `json:"network_state"`
	NetworkState2                  string        `json:"network_state_2"`
	WANState                       string        `json:"wan_state"`
}
